### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#1]
All ideas welcome, including sketches that can be converted into a nicer design later

**Comment by yochannah** [comment]
I had an epiphany. What about a vector test tube or beaker with code bubbling out of it?

**Comment by yochannah** [comment]
Requirements:
- Must be a **vector** graphic. Design in any package you want, but ensure to provide exports in the following formats:
  - SVG
  - PNG
- Bonus points:
  - With "code is science" text
  - without "code is science" text
  - multiple sizes
  - multiple shapes - e.g. long thin landscape rectangle, square for icons, etc.

*If you're interested in this task, I'd suggest discussing your idea or sharing a mock / sketch first to make sure we're on the same wavelength*

**Comment by yochannah** [comment]
All suitable designs will become stickers & be sent to contributors for free. Yay, stickers!

**Comment by itsfreddyrb** [comment]
Yochannah! I'm in!

**Comment by itsfreddyrb** [comment]
Do you have an idea of what you want?

**Comment by yochannah** [comment]
Hey @geekfred ! I'm pretty open to anything honestly - the main thing I'm looking for is that it convey a melding or relationship between code and science. So long as it is a high quality vector, feel free to let your imagination run free! 

I'm utterly in love with rainbows and material ui colours: https://material.io/guidelines/style/color.html#color-color-palette but that is not mandatory. Let me know if you have any ideas, drafts, sketches, or final products!

**Comment by itsfreddyrb** [comment]
Hey! I have some ideas! Let me do some quick sketching and we see what we can get!

**Comment by itsfreddyrb** [comment]
Alright, so I've been playing around and came up with something I wanted to show you. Let me know.
<img width="1207" alt="screen shot 2017-10-09 at 1 37 06 pm" src="https://user-images.githubusercontent.com/7672885/31353201-365ef740-acf7-11e7-9d46-b9d491929d8b.png">
<img width="1179" alt="screen shot 2017-10-09 at 1 36 37 pm" src="https://user-images.githubusercontent.com/7672885/31353204-3701e0e0-acf7-11e7-8b20-446d49e85eb6.png">
<img width="1395" alt="screen shot 2017-10-09 at 1 35 20 pm" src="https://user-images.githubusercontent.com/7672885/31353202-3671eb16-acf7-11e7-89ff-976dace4cdf7.png">
<img width="1553" alt="screen shot 2017-10-09 at 1 34 51 pm" src="https://user-images.githubusercontent.com/7672885/31353203-36b1d424-acf7-11e7-86c7-e7c4df3faefb.png">

**Comment by yochannah** [comment]
I'm in love!! with them ALL!! especially the last three!!!! I may run out of exclamation marks :) 

Feel free to PR them into the /static/ folder - maybe in a subfolder called /logos. I'll try and get some printed as stickers pronto so that I can take them with me to MozFest - if you would like copies, drop me your mailing address at yochannah@gmail.com and I'll arrange to send some over when they are printed.

**Comment by itsfreddyrb** [comment]
Nice! hehe! Ok do you want the last 3? Like, I will send it away but don't you want to pick like an official one? haha...do you like the parenthesis in two colors? or 1 color?

**Comment by yochannah** [comment]
I'd struggle with just one, but if forced to pick it would be number three. It's your choice if you want to PR all or just one, but I'd love to use them all if that works for you - do what you prefer, it's your contribution :) 

 I like the two-colour parenthesis in particular!

**Comment by itsfreddyrb** [comment]
They are all yours! I just wanted to know your pick :D hehe, Yes, number 3 is a bit more academic and formal.

**Comment by leotrs** [comment]
Any word on the stickers? I love the logo and I was thinking about printing my own and just leaving them around, if that's OK @yochannah

**Comment by yochannah** [comment]
@leotrs Yes! please go ahead!

You are entirely welcome to print out your own stickers and distribute them (and thank you!), or if you just want a few I can pop them in the post. I'd love to see some stickers in situ stuck on things!

**Comment by leotrs** [comment]
@geekfred I love the logos and I want to print some stickers based on them! However, I want to maximize the chance of my peers buying into them - can I modify the logos to make them more attractive to practitioners of my field? My field is Network Science - I was thinking of replacing the DNA strand with a network. Looking forward to your response!

**Comment by yochannah** [comment]
My 2c: please upload them to the logo folder if you do! :)

**Comment by itsfreddyrb** [comment]
Of course, this was created for them, so, they command! Ask them hehe...I also have some stuff to help with the look and feel on the website, but work has been exhausting lately. :(
