### ISSUE TITLE
Convert hand-drawn mockup to HTML & CSS - you can choose colours, fonts, etc. 

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#12]
## Task

 Convert [hand-drawn homepage mock](https://imgur.com/a/gs5c3) to basic html and css.  

1. Comment on this task stating that you intend to complete this task
2. When you're ready, add your html mocks to the `static` directory and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble.

## Basic tech and design specs: 
1. Pure native HTML5 & CSS please. No CSS frameworks (e.g. no bootstrap) or font icons (inline svg icons are great though, and can be added to [https://github.com/yochannah/code-is-science/blob/master/static/symbol-defs.svg](https://github.com/yochannah/code-is-science/blob/master/static/symbol-defs.svg)).
2. Bonus points for responsive, but not mandatory!
3. Design: There are no colours in the mocks, so use your own imagination! Try to make them generally go well with logo model 1 or model 2: https://github.com/yochannah/code-is-science/tree/master/static/logos and use material colours: http://materialuicolors.co/
5. Ensure the design is [accessible as possible](https://medium.com/alistapart/writing-html-with-accessibility-in-mind-a62026493412)

### Homepage:
![Mock 1 - homepage](https://i.imgur.com/QPMmsJJ.jpg)
- logo can be found in this repo's /static/logos/model-1 folder
- header with links title text: (don't worry about the correct href value yet, just leave blank) 
  - open source journals
  - contact
  - about
  - search field with magnifying glass icon
- body
  - sidebar with radio box filters
  - main content: 
    - filterable list with headers for journal name, discipline, OSS
    - journal name is a link to an external site
    - oss value is either a checkmark for yes or x for no.
- footer
 - (c) codeisssciencecom 2017
  - links to contact page, twitter @ codeisscience, github.com/codeissscience.

If at any point my handwriting is unclear, please clarify on this issue! 

If you complete this issue, please consider also following on with the second [submit-a-journal page](https://github.com/yochannah/code-is-science/issues/13).

[https://i.imgur.com/QPMmsJJ.jpg](https://i.imgur.com/QPMmsJJ.jpg)

**Comment by shmishtopher** [comment]
I can get to work on this, just one question: Can you please clarify the footer layout?

**Comment by yochannah** [comment]
Hey @shmishtopher and thanks for volunteering to pick it up! sorry, I know the footer is a little bit scribbled-over and messy. It should be just a single straight element with copyright codeisscience and links to contact, twitter, and github - similar to the github footer at the bottom of this issue :) the line I scribbled out shouldn't be in the design.

Does that help?

**Comment by shmishtopher** [comment]
Yes, I'll submit a pr tonight.

**Comment by itsfreddyrb** [comment]
Hey! I know I'm not like an official contributor on this repository hehe, but I would like to look at the design so I can give my $0.02! If you need! Thanks!

**Comment by yochannah** [comment]
Of course, I'd love your input!! :)

**Comment by ikayz** [comment]
Can I still take up this task? It'll be my first contribution to any GitHub project which is not my own. I'm new to open source and GitHub.

**Comment by yochannah** [comment]
@ikayz yes, absolutely! :) shmishtofer made a start on this but I think wasn't able to finish it; you can see the details here: https://github.com/yochannah/code-is-science/pull/15 - it's merged already, but it's up to you if you'd like to continue the work where it dropped off or make your own version

Feel free to ping me here if you have any questions or need any input!

**Comment by ikayz** [comment]
@yochannah I have looked at shmishtofers' code and I'll make my own version. For any questions I'll surely ask you.

**Comment by yochannah** [comment]
Sounds good!

**Comment by yochannah** [comment]
Hey @ikayz! Did you ever get a chance to look at this? (No worries if you didn't, just following up quickly)

**Comment by ikayz** [comment]
@yochannah yes I did have a look at it. I have the assets cloned locally on my laptop. Is it too late for me to work on it and submit? Had a series of events which were beyond my control.

**Comment by yochannah** [comment]
If It works for you, please go ahead! (And thanks!!) If not, that's fine,
it's just nice to free the issue up. <3

**Comment by ikayz** [comment]
Alright thanks

**Comment by ikayz** [comment]
Alright thanks

**Comment by ikayz** [comment]
@yochannah I'm ready to make a pull request so you can have a look at what I worked on.

**Comment by yochannah** [comment]
Pull away - I can't wait!! :D

**Comment by ikayz** [comment]
Made the request

**Comment by yochannah** [comment]
Awesome, and thanks! I'll try to review it tonight (UK time) :)

**Comment by ikayz** [comment]
Alright

**Comment by yochannah** [comment]
Ok, this has been completed thanks to @ikayz's awesome work 😻 😍 💯

**Comment by yochannah** [comment]
@ikayz P.S. - was this your first open source PR?

**Comment by ikayz** [comment]
@yochannah yes it was and I'm proud of it.

**Comment by yochannah** [comment]
omg, that is really cool! well done and THANK YOU!! <3

**Comment by ikayz** [comment]
It was an honour 😃
