### ISSUE TITLE
create html/css mock for code-is-science "add a journal page".

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#13]
This issue follows on from https://github.com/yochannah/code-is-science/issues/12 and should only be completed after https://github.com/yochannah/code-is-science/issues/12 is complete. Use the same design principles and the same header/footer from the previous mock.

![Mock 2 - add a journal](https://i.imgur.com/TAVyi5R.jpg)

### Add a journal page
- header and footer same as homepage
- no sidebar
- main body:
  - form with following text fields
    - journal name
    - journal link
    - discipline (use can type more than one, comma separated)
  - checkbox fields:
    - no
    - unclear / unknown
    - reviewers see source, but code doesn't have to be published openly
    - artifact deposited
    - yes, must have osi-approved licence.
  - submit button. 

form submission functionality will be added later and is not required for this task.

**Comment by HeidiSeibold** [comment]
Have you already started the list somewhere? You could already get it started with e.g. an open google sheet?

**Comment by yochannah** [comment]
Hey @HeidiSeibold! I do have a submission form; it's sadly lacking in responses right now though :( Feel free to add some if you know of any offhand. 

Form: https://goo.gl/forms/ScgFcKJrfIUTBOl83
Responses: https://docs.google.com/spreadsheets/d/1oY5ak7VJa-qwJJeWA3829S-1akZaYtHuWPYpChBdW2o/edit#gid=0

**Comment by HeidiSeibold** [comment]
I submitted two :)

Let me know if you need help promoting the list (e.g. on twitter)

**Comment by yochannah** [comment]
I've added first timers only tags to this issue, as #12 is now complete.

## Newcomers: If you'd like to pick up this issue, here's what to do!

1.  Please look at the code from this PR: https://github.com/yochannah/code-is-science/pull/22
2. Comment on this issue and let me know you're working on it! <3
3. Fork this repo and make a copy of `static/index.html`, then rename it something sensible like `add-a-journal.html` or similar.
4. Modify your new page copy so it looks like the hand-drawn mockup above! 
5. When you're ready, make a PR (guidance here if needed: https://help.github.com/articles/creating-a-pull-request/ )
6. Bask in your awesomeness! 

## If you need help:

 Mention me, @yochannah, tweet me @yoyehudi, or email yochannah@gmail.com.

**Comment by ikayz** [comment]
@yochannah I have decided to work on this one as well.

**Comment by yochannah** [comment]
Sure, go ahead! :)

**Comment by ikayz** [comment]
@yochannah finished working on it. Check PR.

**Comment by yochannah** [comment]
Thanks for letting me know! I'm at a conference but will look at it in a
day or two :)

**Comment by ikayz** [comment]
Alright

**Comment by yochannah** [comment]
fixed by #25
