### ISSUE TITLE
Create list of reasons scientific code isn't open source

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#14]
Session notes are here: https://github.com/yochannah/code-is-science/blob/master/content/posts/mozfest-session-2017.md

We need to: 

1. Create a new folder under the content folder called /reasons (or maybe fears?). 
2. populate fears from the notes doc above, possibly categorised
3. regenerate hugo.

**Comment by aariops** [comment]
I can do it :hand: :smile:

**Comment by yochannah** [comment]
<3
