### ISSUE TITLE
Convert MozFest notes to manifesto draft.

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#17]
Convert [MozFest notes](https://github.com/yochannah/code-is-science/blob/master/content/posts/mozfest-session-2017.md) to manifesto draft.

I'd like community input on this; maybe another workshop session of some sort?

**Comment by yochannah** [comment]
Notes from SSI discussion: we need to include the importance of software citation here!

**Comment by yochannah** [comment]
Software isn't measured only by papers; also by code quality

**Comment by leotrs** [comment]
I like the idea of a manifesto. There are a good few gems in [Best Practices for Scientific Computing](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745) for example,
1. Write programs for people, not computers
2. don't repeat yourself

**Comment by yochannah** [comment]
Update: at [cw18](https://github.com/topics/cw18) we worked on a manifesto draft together and have it open to public consultation until ~June 1. The draft text is here: https://github.com/codeisscience/manifesto/blob/master/manifesto.md

Please feel free to comment, pr, raise issues, etc!

**Comment by JJ** [comment]
OK, let me pick a bone that has troubled me through time here. And full disclosure before I go ahead: I don't like proprietary software in science. Main point is that using proprietary software makes science not reproducible, since you might not be able to use that particular proprietary software (or platform) needed. So my (maybe not so) small proposal would involve slightly changing phrasing so that we talk about "runnable" code to rule out those platforms (if that's what we want, of course. I know *I* do, but...)

**Comment by yochannah** [comment]
@JJ In essence, I agree with you that all scientific code should be open source and that proprietary software shouldn't exist in science at all (at least, I've yet to hear a good argument for highly expensive / closed software yet!) BUT I also want something realistic - and I think more people are likely to adopt the manifesto if it's accepting. so, to my mine:

1) BEST CASE: Paper is published with linked open source code w/ hash of the relevant commit, fixed dependencies, well documented, etc.
2) Not as good but still reasonable: Peer reviewed code before publication, even if the code itself isn't open.
3) Not proper science: accepting papers without actually looking at the code that produced the science.

**Comment by yochannah** [comment]
marking this issue as closed since the manifesto is currently in draft format.
