### ISSUE TITLE
New page: collect resources on good practices and good quality code

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#18]
Create page with list of recommendations for good practice, good quality code.

Some ideas:
 - https://twitter.com/PatSchloss/status/925447629890314241 - tag your github repos with 'reproducible-paper' when published
 - https://software-carpentry.org/ - resources to learn and teach coding practices for scientists. 

People who aren't me: please feel free to add ideas in this issue until we have a genuine page up!

This issue was suggested by @leotrs

**Comment by ha0ye** [comment]
cc @tpoisot

**Comment by yochannah** [comment]
hmm, good heads up. we should link up with (and not duplicate!) https://github.com/tpoisot/ScientificComputingForTheRestOfUs/issues/11

**Comment by ctb** [comment]
Best Practices in Scientific Computing, Wilson et al., 2014 - [link](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745)

**Comment by tpoisot** [comment]
I have a few at the bottom of the readme at https://github.com/tpoisot/ScientificComputingForTheRestOfUs -- would be awesome to have a consistent list!

**Comment by tpoisot** [comment]
PS @yochannah I'm not worried about overlap at all, I think there will be a lot of complementarity!

**Comment by pierrepo** [comment]
[Good enough practices in scientific computing](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005510), PLoS Comput Biol, 2017.

**Comment by samuell** [comment]
There's also [Ten Simple Rules for Developing Usable Software in Computational Biology](https://doi.org/10.1371/journal.pcbi.1005265), PLoS Comp Biol, 2017.

**Comment by leotrs** [comment]
https://github.com/bulutyazilim/awesome-datascience

**Comment by leotrs** [comment]
After we have gathered an initial list, it could be a good idea to try to narrow down the purpose of the list. I'm not worried about overlap either, but we would be better off with a clear objective in mind. Some options.
1. List of tutorials on how to do data science for scientific computing
2. How to write good quality code
3. How to manage a data-intensive scientific project
Best case scenario, we could have resources for all of the above, and indeed I think this is feasible if all we are doing is collecting links.

**Comment by leotrs** [comment]
The author of [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do
) is also a great resource in general: https://twitter.com/jakevdp

**Comment by gramian** [comment]
J. Fehr, J. Heiland, C. Himpe, J. Saak. "Best practices for replicability, reproducibility and reusability of computer-based experiments exemplified by model reduction software". AIMS Mathematics 1(3): 261--281, 2016. https://doi.org/10.3934/Math.2016.3.261

**Comment by synapticlee** [comment]
http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005412

Ten simple rules for making research software more robust

**Comment by yochannah** [comment]
https://figshare.com/collections/Proceedings_of_the_Workshop_on_Sustainable_Software_for_Science_Practice_and_Experiences_WSSSPE5_1_/3869782

**Comment by JJ** [comment]
[Figshare](https://figshare.com) is an excellent resource to publish code. There's also GitXiv, where you can match your ArXiV publication with code in GitHub. Also [OSF](https://OSF.io)

**Comment by yochannah** [comment]
this was implemented nicely by @JJ so closing the issue - thank you so much! <3 

If anyone else wants to view the page it's here: http://www.codeisscience.com/posts/good-practices-code/

or to add / modify for prs: fork & modify: https://github.com/yochannah/code-is-science/blob/master/content/posts/good-practices-code.md
