### ISSUE TITLE
Can we offer code review for scientific code?

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#19]
How would this work?

A few thoughts:
- maybe a list of people with domain expertise (e.g. biology, mathematics, physics) and language expertises?
- is this the right place to do this? Is there somewhere more appropriate? 

Please comment with your thoughts how we could enact this!

This issue suggested by @leotrs

**Comment by leotrs** [comment]
Before taking it up on ourselves to offer this to the wider public, I want to run a local experiment. In the following weeks I want to offer code reviews for people at my lab. I'll see how that goes and report the results here. With that experience we can move on to thinking about the big picture!

**Comment by HeidiSeibold** [comment]
@ropensci does reviews of R packages http://onboarding.ropensci.org/#why-review

**Comment by aath0** [comment]
I really like the idea of scientific code reviewers and having a list of people with domain expertise. 
How about pairing people according to discipline and programming language, so that they can review each other's code? 
I feel that giving some good incentive to review will be important here, as it takes a long time if you want to do it well and it's a big responsibility!

**Comment by yochannah** [comment]
should we make a list of people who have domain expertise and programming
expertise of various sorts? linked to orcid somehow, maybe. Is that even a
feasible thing or insanity?

**Comment by aath0** [comment]
Orcid is a good resource, but I guess it might be hard to mine information from there about the coding that someone did. Maybe if there's a spreadsheet people can write down themselves which programming language and which domain/techniques are within their comfort zone?

I don't know if it's insanity, but I would personally love to have an extra pair of eyes review my code just before submitting work to a journal for example. And I'd be more than happy to take the time and review someone else's code in exchange :)

**Comment by yochannah** [comment]
ooooh, like a group of code review volunteers and / or a resource journals
could use to source reviewers? I like it!!

we could start with a google form for input, I guess. What columns would we
need?

mandatory:
- name
- email address
- domain expertises
- language expertises

optional(?)
- orcid
- github user

anything else?

**Comment by aath0** [comment]
Sounds good :) Maybe in addition to domain expertise there can be the option to include techniques within the domain (for example for me it'd be 'neuroscience' and the technique 'electroencephalography') and in addition to language also have optional packages/toolboxes? I can imaging that reviewing code written around a toolbox that someone is using often is much easier than starting with something completely new :)
