### ISSUE TITLE
Curate list of journals where papers are accompanied by code link/licence

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#2]
start reviewing journals that accept software papers and check the following things (need to consider exact metrics, but here's a start):

- are articles accompanied by code?
  - no code
  - code often found in freeform format so may be hard to tell without careful review, e.g.:
    - source link may be available in text or references
    - attached file in supplementary materials (does this ever happen?)
    - code open source but not linked (may be hard/impossible to tell)
    - code present in elab notebook or other executable snippet
  - code required to submit paper. good example is JOSS: http://joss.theoj.org/about 
  - bonus points for: 
    - OSI licence
    - metadata available describing licence and source link.
    - written in free / open source language 

I'm sure this list will need to be refined.

**Comment by yochannah** [comment]
also consider best format. might be best to go for something simple like a google sheet?

**Comment by yochannah** [comment]
Longer term, I want a nicely service with an API, a UI, and user-specific tokens, but I'd rather get a good idea of the shape of a db record first.

For now, here's the google sheet: https://docs.google.com/spreadsheets/d/1oY5ak7VJa-qwJJeWA3829S-1akZaYtHuWPYpChBdW2o/edit#gid=1946180293 - Anyone with the link can edit; hopefully it won't get spammy and require lockdown

**Comment by yochannah** [comment]
How you can contribute: 
- add more journals to the list (unreviewed or reviewed)
- review journals from the list by stating whether or not they require code for code-related papers.

**Comment by bsipocz** [comment]
the journals of the American Astronomical Society promotes software publications, and usually require at least to cite/name the software packages that were used. It doesn't yet enforce the publication of all the software written to produce the given result, but definitely a welcomed step in the good direction:

http://journals.aas.org/policy/software.html

**Comment by agbeltran** [comment]
Hi @yochannah - are you compiling the journals in the google doc? This blog post seems useful: https://www.software.ac.uk/which-journals-should-i-publish-my-software

**Comment by yochannah** [comment]
@agbeltran Thanks for that link!! I was thinking of maybe spending time on the final hack day at the collaboration workshop reviewing journals to add to https://docs.google.com/spreadsheets/d/1oY5ak7VJa-qwJJeWA3829S-1akZaYtHuWPYpChBdW2o/edit#gid=1946180293 (or maybe even a real db if we have time to set it up) - that link is probably a great place to start

**Comment by synapticlee** [comment]
Would add that Plos computational biology takes software submissions http://journals.plos.org/ploscompbiol/s/submission-guidelines#loc-software-submissions
