### ISSUE TITLE
Science+open source hackathon?

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#21]
So, this is an idea that's been bubbling in my head for some time is that we should probably try to spread the word and get more people to contribute to *academic* open source projects. 

# Idea: 
How about something akin to Hacktoberfest, but specifically aiming to:
1. Draw in academics / scientists / researchers / research software engineers / software devs with an interest in science. 
2. Working on:
    - Open source science projects (this would be easy enough to find with a specific tag)
    - Finding source-less projects references in papers and getting their code online on github, zenodo, etc. 
3. Offer snazzy code is science stickers to all participants + top 20(ish?) contribs get a t-shirt. Or something cooler? Ideas welcome - especially something sciencey. I'm pretty sure I have a source of funding for this, but can try to secure others if needed. 
4. Time period: One month, preferable later in the year. 

# Questions / things to mull over: 
- Names? ScienceSeptember? AcademicApril (or August - I like August better because I want time to spread awareness :D ) maybe something even better? 
- What if this is more popular than planned? Would we find more budget for stickers + postage? 
- Dispatching thanks rewards: I can handle this at small scale but the bigger it gets, the more useful some helpers might be. Anyone wanna help? Helpers will get the snazzy gifts too of course because - oddly - coding isn't just about code! 

### Interested in helping?
Please do any of these: 
- add a comment with thoughts
- volunteer to be an assistant planner / wrangler / postage dispatcher / project manager / designer / community leader / other.

I can dogfood this too and create tasks (demo tasks?) for the repos I work on for this event.

**Comment by andytwoods** [comment]
Happy to help. I ponder if a month is too long (for the first time).

Might be cool to have a 'learn to code' thingo for non-coders.

**Comment by ababaian** [comment]
We're out in Canada, but [hackseq18](http://www.hackseq.com) should be ~October and we have quite a similar mission. We should collaborate.

**Comment by Franknorman** [comment]
I agree that one month may be too long.  cf. Open Access week (October) and Love Data week (Feb).  Have you reached out to other groups active in this area eg http://rse.ac.uk/ ?

**Comment by ocramz** [comment]
Great initiative, I'm eager to participate & help out. Could NumFocus (https://www.numfocus.org/) be a possible source of support/funding?

**Comment by gedankenstuecke** [comment]
I know that the concept is very different, but would maybe a focussed two-day event like the Global Sprint be a better kick-off thing? That way people could also come together in person for working together plus it's a clearer commitment in a sense.

**Comment by ivyleavedtoadflax** [comment]
Love the idea! Has you seen the http://dataopsmanifesto.org/, there may be some ideas you can borrow?

**Comment by JJ** [comment]
Always up for hackathons...
