### ISSUE TITLE
Export .png version of logo with white text

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#23]
## Background

The current mock has a logo with dark text on a dark background. It might be easier to read if the text was white instead.

![image](https://user-images.githubusercontent.com/9271438/37869555-3ab10d96-2fb1-11e8-8eca-758e6718b621.png)

Logos are located here: 
https://github.com/yochannah/code-is-science/tree/master/static/images

## Task

- Export new copies of the logos in the images/model-x folders to .pngs with white text for dark backgrounds. You probably want to open the svg copies and then export to png as they'll be highest quality.
- Ensure that they are named clearly as the light text option. 

## To pick the task up

1. Comment on this issue to let people know you're working on it.
2. Fork this repo
3. Make the changes detailed above, and when ready, make a PR! (guidance here if needed: https://help.github.com/articles/creating-a-pull-request/ )
4. Bask in your awesomeness! 

## If you need help:

 Mention me, @yochannah, tweet me @yoyehudi, or email yochannah@gmail.com.

**Comment by jacksonchui** [comment]
I'll work on this

**Comment by yochannah** [comment]
Awesome! :) Ping me if you have any questions

**Comment by yochannah** [comment]
Resolved by #24 <3
