### ISSUE TITLE
Add favicon to main page

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#27]
I'd like to have a favicon. The main logos are located in the static/images folder and the header template file is [here](https://github.com/yochannah/code-is-science/blob/master/themes/codeisscience/layouts/partials/header.html) - can we convert one of our images into a favicon (maybe one of the no-text logos?)

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi) or if needed email yochannah@gmail.com <3

**Comment by igomez10** [comment]
Hey, I want to work on this issue. Do you mean creating a favicon from this [logo](https://raw.githubusercontent.com/yochannah/code-is-science/master/static/images/logo.png
) and adding it to the template?

or cropping the logo the only have the DNA left side

**Comment by yochannah** [comment]
@igomez10 whatever you think looks best!

**Comment by yochannah** [comment]
Fixed by https://github.com/yochannah/code-is-science/pull/32 Thanks @igomez10 !! 😍
