### ISSUE TITLE
Add links to manifesto and manifesto comments to homepage

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#29]
Manifesto: https://codeisscience.github.io/manifesto/manifesto

I'd like this link to be really prominent (maybe in a button or something) here: https://github.com/yochannah/code-is-science/blob/master/content/_index.md 

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi) or if needed email yochannah@gmail.com <3

**Comment by Tlazypanda** [comment]
Hey @yochannah I would be interested in taking up this issue! 😄

**Comment by yochannah** [comment]
@Tlazypanda awesome! go go go! 😍 Let me know if you have any Qs

**Comment by yochannah** [comment]
@Tlazypanda did you ever have any luck with this? I can help if needed

**Comment by ZediWards** [comment]
@yochannah, I would like to take a crack at this one. This would be my first open source contribution :)

**Comment by yochannah** [comment]
@ZediWards go ahead & let me know if you need any help of have any questions!

**Comment by ZediWards** [comment]
I made a mock up of the index page with a button to the manifesto. At the break point where the sidebar falls to the bottom of the page the manifesto button will stay on the top of the page aligned to the right of the header "Code is Science". Thoughts or feedback?

![button1](https://user-images.githubusercontent.com/33021719/45276763-3d366500-b492-11e8-8afe-11167a2014e2.jpg)

**Comment by yochannah** [comment]
@ZediWards This is great - I love it! Could we make the words in the button "Read and sign the manifesto!" (hmm, or is that too long? 😁)

Do you need any help to go ahead and implement + make the pull request? :)
