### ISSUE TITLE
Add citation guidelines for this repo

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#30]
ideally using https://citation-file-format.github.io/ to get there.

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by sliceking** [comment]
Hi, I'd like to help with this but I'm not sure what metadata to include in the .cff

**Comment by yochannah** [comment]
@svwielga4 for author, you could start with referencing my details from my github profile if that's handy? 

project: code is science
version... 1.0 I guess? 
date release.... 1 october 2017

is that enough to go on?

**Comment by sliceking** [comment]
awesome! thank you = )

**Comment by JJ** [comment]
Added a citation.bib to my PR, just in case you want to check it out.

**Comment by yochannah** [comment]
@JJ thanks for the citation.bib! @svwielga4, thanks for the cff!

**Comment by JJ** [comment]
:+1:
