### ISSUE TITLE
Add credits to site footer

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#31]
We used [icomoon](https://icomoon.io/app/#/select) & [hugo](https://gohugo.io/) to get up and running! Let's add links to these in the footer of the page, here: 

## Getting started.

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by sarahchima** [comment]
I want to work on this task.

**Comment by yochannah** [comment]
@sarahchima You are brilliant! Go go go - let me know if you have any questions!!

**Comment by suleka96** [comment]
I would also like to give this a try

**Comment by yochannah** [comment]
@sarahchima how did you get on with this - did you manage to get the css to work? 

@suleka96 I'd like to give @sarahchima a chance to look at this first if you don't mind <3 thanks for the offer though!

**Comment by rddravic** [comment]
@yochannah : Hi, I would like to give my contributions to codeisscience. I'm a beginner

**Comment by yochannah** [comment]
@rddravic Sure, go ahead! This issue still needs to be done. There are some instructions for building the css and site on the wiki https://github.com/yochannah/code-is-science/wiki

Let me know if you have any questions or need help getting started.

**Comment by rddravic** [comment]
@yochannah : Can I have more clarity on what needs to be updated. I see many files having footer links. Can I have any preview attachment kind of

**Comment by yochannah** [comment]
@rddravic This is the file: https://github.com/yochannah/code-is-science/blob/master/themes/codeisscience/layouts/partials/footer.html perhaps some text like

"Icons by Icomoon and site generated by Hugo" (with links to icomoon/hugo) would be perfect.
