### ISSUE TITLE
Create code reviewer database

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#35]
See https://github.com/yochannah/code-is-science/issues/19 for the discussion leading up to this. Implementation method is up to you - this could be google sheets and a script to read from them as needed. This option is good because it requires minimal setup / paid hosting. You can see @ha0ye's approach to the google sheets option here: https://github.com/yochannah/code-is-science/pull/33 

We would like to offer a list of people who are interested in and able to review code, showing the following details: 

mandatory:
- reviewer name
- email address
- domain expertises
- specific techniques within the domain
- language expertises
- language-specific tools or packages

optional(?)
- orcid
- github user

**Comment by aath0** [comment]
Glad this is moving forward! Let me know if I can help somehow :)

**Comment by yochannah** [comment]
I am *so* grateful for your help in thinking and talking through the idea!
Hopefully @ha0ye's R approach to the journal list can be applied here, too,
when we get the chance. 😄

**Comment by yochannah** [comment]
We also need to have a user's credentials (_why_ is this person qualified to review these topics?) . Can this be pulled via API from orchid? possibly, but it might require auth. The other option is to ask them to list it manually in some brief way.

**Comment by ha0ye** [comment]
Could mirror what the @ReScience org is doing for reviewer applications:
https://github.com/ReScience/ReScience/issues/27
