### ISSUE TITLE
Site header: doesn't wrap well on small screens

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#39]
See screenshot below - the list content doesn't wrap nicely. We could probably shrink the logo margins and make things wrap a bit better, maybe with some flexbox layout instead of floats. Docs on how to update the site and build the css are here: https://github.com/yochannah/code-is-science/wiki 

![image](https://user-images.githubusercontent.com/9271438/40281135-6dda112e-5c55-11e8-826a-1c3624be5a28.png)

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory and email me your address if you'd like to have some codeisscience stickers for your trouble. <3

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by DustinsCode** [comment]
Hello! I would like to give this task a shot for my first open source contribution, if that's okay!

**Comment by abhiabhijit** [comment]
#30 

Hello You can use media queries, to handle the  Screen width related issues.

I have modified your header part and rebuild it using Flex and media queries.

I have also added font-awesome icons to the titles if you dont like them , you can remove it, but the purpose of your problem is served

Here is the [link](https://github.com/abhiabhijit/GithubContributions-/blob/master/Respnavbar.html) of the code

Thank You!

**Comment by yochannah** [comment]
The files you probably need to edit for this are the less file, here: https://github.com/yochannah/code-is-science/tree/master/themes/codeisscience/static/css 

@abhiabhijit thanks for giving this a go!  @xStaticVoid offered to look at this first so I'd rather give them the chance to have a look first, if you don't mind :) but if you'd like, I have an issue for adding icons, here: 

@xStaticVoid You still up for this? If so, please go ahead and let me know if you have any questions. 
You'll need to fork this repo (top right corner) and make the changes. Ping me with any questions! 

Thank you both for volunteering! <3

**Comment by DustinsCode** [comment]
@yochannah I am! I wanted to wait until I received word to work on it.  I'll start when I get home from work tonight! Thanks! :)

**Comment by yochannah** [comment]
Yay, brilliant!

**Comment by alokpant** [comment]
@xStaticVoid Not sure if you have already fixed it, I was working on https://github.com/yochannah/code-is-science/issues/42 and had to also fix the navigation as part of my changes. PR is here: https://github.com/yochannah/code-is-science/pull/43 
cc: @yochannah

**Comment by alokpant** [comment]
Sorry for the confusion, it is already merged. 👍 I got confused because of reference.

**Comment by alokpant** [comment]
If issue is fixed, will it be possible to close it to avoid future confusions? @yochannah

**Comment by yochannah** [comment]
whoops, you're right, I should have closed this - thanks for the heads up @alokpant  and thanks @xStaticVoid for the fix! :)
