### ISSUE TITLE
add icons for the nav links in the top bar

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#40]
We use inline icomoon svg icons already in the contact page, so it would be nice to keep things consistent. @abhiabhijit, would you like to give this a go? :) 

First, fork the repo, then in your fork of the repo, add icons.

### to add icons:

1. go to the [icomoon](https://icomoon.io/app/#/select) app and select relevant icons for each of the links
2. click generate svg & more on the bottom bar of icomoon
3. hover over an icon and click the "get code" to get the svg code for the icon, like this:  ![image](https://user-images.githubusercontent.com/9271438/40390172-403d7bee-5e0c-11e8-8995-549fd08f1005.png)
4. paste the symbol definition here:  https://github.com/yochannah/code-is-science/blob/master/themes/codeisscience/static/symbol-defs.svg?short_path=543107f
5. paste the "html svg use" code where you want the icon to appear in the code. You can look at the raw code for the contact page for more examples of how this works: https://raw.githubusercontent.com/yochannah/code-is-science/master/content/contact.md 

Finally, when it's all done, make a PR!

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [gitter](https://gitter.im/codeisscience/Lobby) or if needed email yochannah@gmail.com <3

**Comment by abhiabhijit** [comment]
I am Interested in doing it.

**Comment by yochannah** [comment]
@abhiabhijit brilliant. Please go ahead and let me know if anything isn't clear. Quick warning- I'm out at my brother's wedding from tonight until Monday evening, so I may not answer questions over that period.

**Comment by yochannah** [comment]
@abhiabhijit How are you getting on with this one? Can I help at all? :)

**Comment by ikayz** [comment]
@yochannah do you still need someone to work on this issue?

**Comment by yochannah** [comment]
@ikayz I think it should be ok to pick this one up if you like. Thanks! :)

**Comment by ikayz** [comment]
@yochannah alright I'm on it 😃

**Comment by ikayz** [comment]
@yochannah I was working out the icons issue over the weekend, I need a little help from you. The icons you inserted on the codeisscience web site. Did you explicitly specify the link of the icons in the code?

**Comment by yochannah** [comment]
sorry for the slow reply on this - rushing about and far too busy. If you look at the code for the [contact page](https://raw.githubusercontent.com/yochannah/code-is-science/master/content/contact.md) does it help at all? the `<use>` tags go in the place you want the code to show up, and the symbol definition goes in the symbol-defs.svg file

**Comment by ikayz** [comment]
Alright will try using that today, been quite tied up over the passed days...

**Comment by yochannah** [comment]
No rush! :)

**Comment by ikayz** [comment]
Awesome

**Comment by ikayz** [comment]
@yochannah  I have added the icons, they are now working. Refer to journal_table.html

**Comment by bhavesh-g** [comment]
I will add icons to nav on all pages.

**Comment by yochannah** [comment]
@bhavesh-g thanks for the offer! I think @ikayz has actually done it, I just need to get around to reviewing the PR - sorry! :)
