### ISSUE TITLE
Contact info doesn’t wrap well on small screens

### ISSUE THREAD

**Issue by KirstieJane** [codeisscience/code-is-science#42]
## Describe the issue in as much detail as possible

Rather similar to the header not wrapping well on small screens (as described in #39) the boxes containing information on how to contact Code is Science don’t wrap well on small screens.

## What page(s) does it occur on?

The contact page on the website: http://www.codeisscience.com/contact/

Here are some screenshots from my iphone (sorry if they render super huge!!)

![4f910452-5418-4e23-8258-c801fcf0cfe8](https://user-images.githubusercontent.com/3626306/40406165-8cf8b2aa-5e57-11e8-9b4a-d1bab4b1f853.png)
![1dd116d5-382d-41cf-b45b-562489b0acc1](https://user-images.githubusercontent.com/3626306/40406166-8d22d292-5e57-11e8-89f5-31f8e6765dd2.png)

**Comment by alokpant** [comment]
There seems to be responsive issues with the website. If this is available, I would like to help out @yochannah

**Comment by yochannah** [comment]
@mind3less I would love that, thanks! I'm on holiday at my brother's
wedding right now so I might not be able to respond properly until next
week but maybe one of the other contributors will be able to help if you
have any questions or make a PR <3

**Comment by alokpant** [comment]
@yochannah No worries. Please enjoy the wedding. Best wishes for married couple. I will create PR and let it there for review.

**Comment by yochannah** [comment]
Thanks for fixing this, @alokpant!
