### ISSUE TITLE
journal page - make it include the header include file [interesting mix of R and hugo templating]

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#44]
So, the site is built largely using [hugo](https://gohugo.io/) with the exception of the journals page, which is rendered using [knitr](https://yihui.name/knitr/) R-related wizardry. @alokpant wisely suggested that the journals page should use the same header, which is entirely sane. Offhand I'm not sure how to mate the hugo template with the R template, or even if it's possible, but it would be nice if we could do so.

Relevant files: 

- R journal page template: https://github.com/yochannah/code-is-science/blob/master/R/template.html
- R script that does the rendering: https://github.com/yochannah/code-is-science/edit/master/R/journal_table.Rmd 
- header file for hugo: https://github.com/yochannah/code-is-science/blob/master/themes/codeisscience/layouts/partials/header.html

And you can check out the [wiki](https://github.com/yochannah/code-is-science/wiki) for instructions on how to build the site.

**Comment by alokpant** [comment]
@yochannah I will do some research to see if this is possible or not.

**Comment by alokpant** [comment]
@yochannah I have not worked with RStudio and knitr before. I will look into it again. However if anyone has more idea around Rstudio then this is also free to be taken. 

I was trying around https://github.com/alokpant/code-is-science/pull/2, and few things that came up:
1. Most of styling in page is same, so we can create a single Less file and then import it.
2. Journal table has few plugin dependencies. So it would be good to create a vendor folder and add those dependencies there. The ones I know are:
- jQuery (required for DataTable)
- DataTable

This would contain necessary files (CSS or JS or both)

Using Data-uri is nice, but it makes code really unreadable ( and I also have no idea where [this](https://github.com/alokpant/code-is-science/pull/2/files#diff-24ee3a0f102215af7cfe5d633d271c15L48) is generated).

This would help not to repeat same code in multiple places.

**Comment by jamessandy** [comment]
Hello @yochannah can you please give me an issue to work on
