### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by alokpant** [codeisscience/code-is-science#45]
When submitting a PR, if there is a predefined template, then it would make it easier for developers to outline changes. As references between PR (s) and Issue(s) are documented within Github, so in long run it will also make it easier to close already solved issues.

For now it would make sense to just create a PR template. Github has good documentation on how to create it [here](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/).

Once alot of users start adding issues or feature requests we can make use of inbuilt Github feature. When user clicks on **Issue** it will ask for whether it is issue or feature. Below is sample, I create for one of other projects:

![image](https://user-images.githubusercontent.com/6135761/40885688-8bd0ca66-672b-11e8-981b-f687ba625f8c.png)

**Comment by alokpant** [comment]
For now, it would be nice to have a simple PR template. My suggestion would be to include:

```
Fixes Issue#
Link of issue here

### Changes

Summary of changes you made.

* Change 1
* Change 2

### Test plan

Explain how to test changes you made.

* [ ] Step 1
* [ ] Step 2

### Demo (optional)
Sreenshots (before & after) or video that show result of your work.
```

Example based on my last PR would be:

---

Fixes #
https://github.com/yochannah/code-is-science/issues/42

### Changes

Summary of changes you made.

* Make contact us Links adapt to smaller screens
* Fix menu items for smaller and medium devices
* Add proper two column layout to pages

### Test plan

Explain how to test changes you made.

* http://www.codeisscience.com/contact/
* Reduce size of browser to see how it appears on mobile


### Demo (optional)

**Desktop:**
![image](https://user-images.githubusercontent.com/6135761/40885753-da872c62-672c-11e8-87dd-4a6876aa3494.png)

---- 

**Mobile**
![image](https://user-images.githubusercontent.com/6135761/40885759-e5685548-672c-11e8-8a0e-26cc0a6b4544.png)

----

![image](https://user-images.githubusercontent.com/6135761/40885768-f89a9914-672c-11e8-9082-677d44c57137.png)

**Comment by alokpant** [comment]
I have also updated my closed PR with this template: https://github.com/yochannah/code-is-science/pull/43

**Comment by alokpant** [comment]
Another sample of PR template:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**System (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
```

**Comment by alokpant** [comment]
@yochannah If it makes sense, then I can create PR template.

**Comment by yochannah** [comment]
I have no words for how awesome you are! My one comment is to remember that not all prs are bug related - they could be new features or docs or something else :) but please go ahead!!

**Comment by alokpant** [comment]
@yochannah Absolutely. As I mentioned above, there is a way to choose between **Issue** vs **Feature/Enhancement Request** when new issue is selected. However all of them will be listed under [Issue](https://github.com/yochannah/code-is-science/issues) section. Only templates will be different.

When submitting a PR, as far as I know there is no way to differentiate between a bug or a new feature. So as long as there is an Issue (whether bug or Feature Enhancement) above template will work.

**Comment by yochannah** [comment]
Sounds good!
