### ISSUE TITLE
Footer link colour doesn't contrast very well [css fix needed]

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#48]
See screenshot - dark purple on dark blue doesn't work too well :D can we make it a more readable colour?

![image](https://user-images.githubusercontent.com/9271438/40889970-049557b0-6767-11e8-99d6-2e4b5026e6c5.png)

**Comment by alokpant** [comment]
@yochannah I can look at this. I would also suggest to increase font-size to 16px, as 12px is barely visible nowadays. With increasing resolution of laptop, 16px looks much readable than others.

**Comment by yochannah** [comment]
Sounds good, and thanks!
