### ISSUE TITLE
Create cumulative user-editable db

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#5]
This will allow contributors to add / update reviews for the various journals

**Comment by yochannah** [comment]
Loose specs: 
- Needs to be an open source DB.
- I'm not sure of the schema yet and it *will* have columns added to it over time. Does this mean a document store might be a good idea? Open to anything really. Current columns are very minimal: https://docs.google.com/spreadsheets/d/1oY5ak7VJa-qwJJeWA3829S-1akZaYtHuWPYpChBdW2o/edit?usp=drive_web 
- Somewhere free to host it would be nice but not mandatory.

**Comment by stain88** [comment]
Hi :wave:
Regarding free to host, you could potentially have a folder in this repository, and then use GitHub's API (https://developer.github.com/v3/repos/contents/) to get/post updates to the DB.
Otherwise, a self-contained DB could be hosted on e.g. https://www.heroku.com/

**Comment by JJ** [comment]
Heroku can only use postgreSQL if you don't want to introduce your credit card. If it's a lightweight thing, and we want same people with access to the site to have access to the DB, we could just use a bunch of JSONs right here in the repository. Change each JSON with a commit, and you even have rollback capability. You can use that easily from static pages, and even add search capabilities in the frontend.

**Comment by yochannah** [comment]
@JJ  I love the idea of PRs for json but I'm worries it wouldn't be accessible enough for not technical users - I think we'd need a proper db or at least a google form (but I think a db is probably easier to manage)

**Comment by ha0ye** [comment]
So, regarding accessibility... what are the loose specs there? It seems like anything with formal DB would be difficult for non-technical folks to deal with (esp. if it requires specialized software).

I like Google Sheets as a general point of entry. Initial thoughts here if you need programmatic access is the R package for dealing with google sheets, then adding a few lines to Travis CI to run any necessary scripts?

**Comment by yochannah** [comment]
@ha0ye I'm open to *any* implementation so if R sounds doable then that's great! I agree it's important to not add technical barriers, as well. Do you need anything frmo me to start down the R route? I'l invite you as a contributor

**Comment by ha0ye** [comment]
@yochannah Yeah, R is good for me, and I've been meaning to play around a bit with CI usage anyway. Would the basic goal be to render a page for the website with a table for the DB? It could be static or deploy something fancier, e.g. by using flexdashboards: https://rmarkdown.rstudio.com/flexdashboard/index.html

**Comment by yochannah** [comment]
@ha0ye yes! I also have a mock for the page look here: https://github.com/yochannah/code-is-science/blob/master/static/mocks/index.html

**Comment by JJ** [comment]
Problem with Google Spreadsheets, or any other online thing for that
matter, is to render it in whatever format the page is in.
Anyway, what's the use case here? We can have people submitting pull
requests with new resources in table form, for instance, and then hugo-ize
that simple table into a web page, or else create a script that can do
that. It does not get simpler than markdown and push-button pull requests.

**Comment by yochannah** [comment]
I've met quite a few people who are intimidated by the github interface and how to write markdown. It's possible that academics who care about open source code do know markdown and github, but I don't want to exclude those who don't know github if at all possible. I think @ha0ye was going to use the R API to read from the spreadsheet, and we can use a google form to write to the spreadsheet so I don't think format is too big a problem

**Comment by JJ** [comment]
OK :-) Great idea.

You'll need to have the R code hosted somewhere, though... You can read
Google Spreadsheet data, if it's public, using client-side javascript. I
don't really know if you're looking for a hosted solution, or simply have
something hosted here, in GitHub. Since my funding is not regular, I tend
to look for solutions that are self-hosted and self-mainained and, if
possible, free.

**Comment by ha0ye** [comment]
My current thinking is that the CI can run the R scripts alongside anything else to generate the website. My lab currently uses a similar workflow for automated analyses on continually updating data (https://github.com/weecology/portalpredictions), so it's fairly straightforward for me to port some of the ideas over to here.

Would still need some sort of hook to auto-rerun CI upon updates to the google sheet, but that seems like not a huge technical hurdle, and could always be done manually if there's vetting of the form input anyway.

**Comment by JJ** [comment]
You can configurate forms so that they send you an email every time
somebody answers, right?

**Comment by yochannah** [comment]
This issue was closed by the above PR.
