### ISSUE TITLE
Update manifesto page to either contain manifesto or link to manifesto

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#51]
So, I'm about to print some leaflets and a poster with the url codeisscience.com/manifesto as the main entry point.  That currently exists as manifesto.md in the root of the content folder here.

We could do one of the following: 

 - either
     - copy [the text](https://codeisscience.github.io/manifesto/manifesto) to manifesto.md in this repo
     - add links to pledge support as organisation and as individual,
     - add links to posters / leaflets  
 - ALTERNATIVELY: Figure out how to just redirect from codeisscience.com/manifesto to [the manifesto](https://codeisscience.github.io/manifesto/manifesto) <-- this is my preferred option in all honesty, but without access to the server (e.g. since it's hosted on github) I don't think that it's possible to [301 redirect](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections) which leaves us with a meta-refresh which isn't best practice. Maybe I am fussing over nothing and we should just add a meta refresh to the page.

**Comment by yochannah** [comment]
Forgot to add - this needs be done by ~June 20th at the latest in time for my talk at GCCBOSC!  I would be grateful for someone else's opinion on the matter if possible as I'm having trouble deciding :)

**Comment by JJ** [comment]
But right now codeisscience.com is generated directly from the markdown
using Hugo, right? You can probably generate the HTML page directly
bypassing Hugo and insert a 301 header in the HTML code, if I'm not wrong,
right?

**Comment by yochannah** [comment]
I think http status codes are generated by the server and can't be provided by HTML content, but I could be mistaken.

**Comment by JJ** [comment]
You can do this:

<meta http-equiv="refresh" content="0; url=http://example.com/" />



I think most, or any, HTTP status codes generated by the server can be
embedded in web pages, precisely for this kind of situations. See here:
https://stackoverflow.com/questions/5411538/redirect-from-an-html-page

**Comment by JJ** [comment]
Also this, but it uses Jekyll, and I don't know if it will be applicable
here... https://help.github.com/articles/redirects-on-github-pages/

**Comment by JJ** [comment]
And this is Hugo specific:
https://discourse.gohugo.io/t/url-redirect-forwarding/4689/2

**Comment by yochannah** [comment]
This is complete, implemented with meta refresh and js so hopefully one should work even if the other fails for some reason: https://github.com/yochannah/code-is-science/commit/0a9695efba4f8c569d26176a62ab39d92016415e
