### ISSUE TITLE
Add all sprint contributors using the all-contributors bot

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#76]
I'm experimentally trying out the bot that @JPTIZ and @rgaiacs set up - see https://github.com/codeisscience/code-is-science/pull/65#issuecomment-686058960

**Comment by yochannah** [comment]
@all-contributors please add @JPTIZ for tool, code, infra, maintenance

**Comment by yochannah** [comment]
@all-contributors please add @rgaiacs for mentoring infra, maintenance, bugs

**Comment by yochannah** [comment]
@all-contributors please add @ikayz for design, code, content

**Comment by yochannah** [comment]
@all-contributors please add @Fnyasimi for review, projectManagement, question

**Comment by yochannah** [comment]
@all-contributors please add @abigail-wood for content, question

**Comment by yochannah** [comment]
@all-contributors please add @delwen for content, question

**Comment by yochannah** [comment]
@all-contributors please add @dipanshunagar for content, question, code

**Comment by yochannah** [comment]
@all-contributors please add @emmyft for ideas

**Comment by yochannah** [comment]
@all-contributors please add @helenapv for ideas

**Comment by yochannah** [comment]
@all-contributors please add @StuartRFKing for ideas

**Comment by yochannah** [comment]
@all-contributors please add @billbrod for ideas, content

**Comment by JPTIZ** [comment]
Did we miss someone?

**Comment by yochannah** [comment]
I think this is complete :)
