### ISSUE TITLE
Why aren't the emoji for the all contributors bot showing correctly? 

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#87]
For some reason the emoji contribution key under the all contributors section on the site doesn't seem to be working - see the screenshot 
![image](https://user-images.githubusercontent.com/9271438/92130333-84932a00-edfc-11ea-9d29-4d8aaf91e25d.png)

**Comment by JPTIZ** [comment]
I'm also wondering this. And looking at the README.md's allcontributors HTML part it really doesn't include anything related to emojis:

```html
<table>
  <tr>
    <td align="center"><a href="http://rgaiacs.com"><img src="https://avatars0.githubusercontent.com/u/1506457?v=4" width="100px;" alt=""/><br /><sub><b>Raniere Silva</b></sub></a></td>
    <td align="center"><a href="https://github.com/JPTIZ"><img src="https://avatars2.githubusercontent.com/u/11988816?v=4" width="100px;" alt=""/><br /><sub><b>João Paulo Taylor Ienczak Zanette</b></sub></a></td>
    <td align="center"><a href="https://ikayz.github.io/"><img src="https://avatars1.githubusercontent.com/u/31007212?v=4" width="100px;" alt=""/><br /><sub><b>Isaac Miti</b></sub></a></td>
    <td align="center"><a href="https://github.com/Fnyasimi"><img src="https://avatars3.githubusercontent.com/u/41294948?v=4" width="100px;" alt=""/><br /><sub><b>Fnyasimi</b></sub></a></td>
    <td align="center"><a href="http://biomake.space"><img src="https://avatars1.githubusercontent.com/u/15981287?v=4" width="100px;" alt=""/><br /><sub><b>Abigail Wood</b></sub></a></td>
    <td align="center"><a href="https://github.com/delwen"><img src="https://avatars0.githubusercontent.com/u/18604247?v=4" width="100px;" alt=""/><br /><sub><b>Delwen Franzen</b></sub></a></td>
    <td align="center"><a href="http://twitter.com/dipanshunagar"><img src="https://avatars0.githubusercontent.com/u/10234389?v=4" width="100px;" alt=""/><br /><sub><b>Dipanshu Nagar</b></sub></a></td>
  </tr>
  <tr>
    <td align="center"><a href="http://twitter.com/emmy_ft"><img src="https://avatars1.githubusercontent.com/u/24935760?v=4" width="100px;" alt=""/><br /><sub><b>Emmy Tsang</b></sub></a></td>
  </tr>
</table>
```

**Comment by yochannah** [comment]
maybe we are missing a config of some sort?

**Comment by JPTIZ** [comment]
I'm checking [this repo](https://github.com/Berkmann18/json-fixer/) to see if I find relevant differences, but there appears to be none altought the PRs generated from the bot do insert the emojis (see [this example](https://github.com/Berkmann18/json-fixer/pull/9/files))

**Comment by JPTIZ** [comment]
Just making a little comparison here of the .all-contributorsrc's keys (except for ones like project name):

| Key | json-fixer repo                  | Code is science repo                                                                                                                                                                                            |
| --- | ---------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| `"badgeTemplate"` | `<none>                          ` | `"[![All Contributors](https://img.shields.io/badge/all_contributors-<%= contributors.length %>-orange.svg?style=flat-square)](#contributors)"                                                ` |
| `"commit"` | `true                  ` | `false                                                                                                                                                                                               ` |
| `"contributorTemplate"` | `<none>                          ` | `"<a href=\"<%= contributor.profile %>\"><img src=\"<%= contributor.avatar_url %>\" width=\"<%= options.imageSize %>px;\" alt=\"\"/><br /><sub><b><%= contributor.name %></b></sub></a>"` |
| `"commitConvention"` | `"angular"`    | <none> |
| `"contributorsPerLine"` | `7        ` | `7                                                                                                                                                                                      ` |
|`"contributorsSortAlphabetically"` | `<none>                          ` | `false                                                                                                                                                                       ` |
| `"imageSize"` | `100                ` | `100                                                                                                                                                                                              ` |
| `"repoHost"` | `"https://github.com"` | `"https://github.com"                                                                                                                                                                               ` |
| `"repoType"`| `"repoType": "github"            ` | `"github"                                                                                                                                                                                          ` |
| `"skipCi"` | `true                  ` | `true                                                                                                                                                                                                ` |
| `"types"` | `<none>                          ` | `{ "custom": { "symbol": "🔭", "description": "A custom contribution type.", "link": "[<%= symbol %>](<%= url %> \"<%= description %>\")," } }                                                        ` |

**Comment by JPTIZ** [comment]
Looking at the table above, it seems that we're overriting the emoji insertion by setting a custom `contributorTemplate` key. There is probably a way to tell to insert the emojis somewhere if we still wanna use a custom template, but in a quick look we could simply remove it as apparently we're not making anything different from the standard (except for emojis).
